language: node_js
node_js: 
  - 8.11.4 
cache:
  directories:
    - node_modules

branches:
  only:
    - blog 

before_install:
  - npm install -g hexo-cli

install:
  - npm install
  - npm install hexo-deployer-git --save

script:
  - hexo clean
  - hexo generate

after_script:
  - git config user.name "houugen"
  - git config user.email "lzm-6121@163.com"
  - sed -i "s/repo_token/${REPO_TOKEN}/g" ./_config.yml
  - hexo deploy
